### ISSUE TITLE
assert proto in H2_NPN_PROTOCOLS or proto == H2C_PROTOCOL AssertionError

### ISSUE THREAD

**Issue by acecilia** [Pr0Ger/PyAPNs2#8]
Hi,
While using PyAPNs2 I am facing an error from hyper. I searched but could not find any related information. Did this happen to you?

`>>> from apns2.client import APNsClient
>>> from apns2.payload import Payload
>>> token_hex = 'theTokenNumbers'
>>> payload = Payload(alert="Hello World!", sound="default", badge=1)
>>> client = APNsClient('key.pem', use_sandbox=False, use_alternative_port=False)
>>> client.send_notification(token_hex, payload)
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "/home/alejo/.virtualenvs/worktoday/lib/python2.7/site-packages/apns2/client.py", line 34, in send_notification
   stream_id = self.__connection.request('POST', url, json_payload, headers)
 File "/home/alejo/.virtualenvs/worktoday/lib/python2.7/site-packages/hyper/http20/connection.py", line 188, in request
   self.endheaders(message_body=body, final=True, stream_id=stream_id)
 File "/home/alejo/.virtualenvs/worktoday/lib/python2.7/site-packages/hyper/http20/connection.py", line 374, in endheaders
   self.connect()
 File "/home/alejo/.virtualenvs/worktoday/lib/python2.7/site-packages/hyper/http20/connection.py", line 260, in connect
   assert proto in H2_NPN_PROTOCOLS or proto == H2C_PROTOCOL
AssertionError`

Thanks!

**Comment by Pr0Ger** [comment]
No, this didn't happen to me, but I use only Python 3.5 in my projects, so maybe it's a reason.
I found some issues related to connection problems with APNs and one of them especially about this assert, did you saw it? Lukasa/hyper#197 Lukasa/hyper#213

**Comment by acecilia** [comment]
Just red about it. This seems crazy tricky for just sending push notifications :(
I think I am giving up on using PyAPNs2 and hyper for now, will look for alternatives. thanks for your work!

**Comment by Pr0Ger** [comment]
OK, I can point you in a right direction anyway. Apple doesn't disable old push API (via binary protocol), so [this library](https://github.com/djacobs/PyAPNs) should work for you
