### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by fbartolom** [Pr0Ger/PyAPNs2#91]
When I try to execute the script linking the library I get a syntax error:

Traceback (most recent call last):
  File "remotenotifications.py", line 1, in <module>
    from apns2.client import APNsClient
  File "/var/www/html/iPhone/tags/apns2/client.py", line 50
    credentials: Union[Credentials, str],
               ^

**Comment by aaugustin** [comment]
This library requires at least Python 3.5. You're probably using an older version of Python.
